import { FiArrowRight } from "react-icons/fi";
import { Card } from "./ProfileParts";

export default function Security() {
  return <div className="space-y-6">
    <Card className="grid items-center gap-6 lg:grid-cols-[32%_1fr]"><h2 className="font-semibold">Change password</h2><div className="flex items-center gap-6"><label className="flex-1 rounded-lg border border-[#E5E7EB] px-3 py-2 text-[10px] text-[#6C737F]">Password<input type="password" className="block w-full bg-transparent pt-1 text-xs text-[#111927] outline-none" /></label><button className="cursor-pointer px-2 text-xs text-[#635BFF]">Edit</button></div></Card>
    <Card><h2 className="font-semibold">Multi Factor Authentication</h2><div className="mt-4 grid gap-6 md:grid-cols-2">{[{ name: "Authenticator App", description: "Use an authenticator app to generate one time security codes." }, { name: "Text Message", description: "Use your mobile phone to receive security codes via SMS." }].map((method) => <div key={method.name} className="rounded-2xl border border-[#F2F4F7] p-5"><span className="flex items-center gap-2 text-xs text-[#F04438]"><span className="size-1.5 rounded-full bg-[#F04438]" />Off</span><h3 className="mt-3 text-xs">{method.name}</h3><p className="mt-2 text-xs leading-5 text-[#6C737F]">{method.description}</p><button className="mt-6 flex cursor-pointer items-center gap-2 rounded-lg border border-[#C6C2FF] px-4 py-2 text-xs text-[#635BFF]">Set Up <FiArrowRight /></button></div>)}</div></Card>
    <Card className="!overflow-hidden !p-0"><div className="px-5 pb-4 pt-6"><h2 className="font-semibold">Login history</h2><p className="text-xs text-[#6C737F]">Your recent login activity</p></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="bg-[#F8F9FA] text-[10px] uppercase text-[#384250]"><tr><th className="px-4 py-3">Login type</th><th className="px-4 py-3">IP address</th><th className="px-4 py-3">Client</th></tr></thead><tbody>{["08:14", "05:54"].map((time) => <tr key={time} className="border-t border-[#F2F4F7]"><td className="px-4 py-4 leading-5">Credential login<br />on {time} AM 01/31/2024</td><td className="px-4 py-4">95.130.17.84</td><td className="px-4 py-4">Chrome, Mac OS 10.15.7</td></tr>)}</tbody></table></div></Card>
  </div>;
}
